version: '3.8'

services:
  # PostgreSQL база данных
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: read_zone_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d read_zone_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nuxt.js приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=read_zone_db
      - VITE_BACK_URL=http://localhost:3000
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads  # Для загруженных файлов

volumes:
  postgres_data:
